### ISSUE TITLE
Version Jackie Roadmap

### ISSUE THREAD

**Issue by kurtwheeler** [data-refinery/data-refinery#122]
@jaclyn_taroni and I had a discussion on Wednesday to discuss what we should target to get done and in what order for version Jackie. We identified three milestones, which once completed will result in what has been referred to as version Jackie.

#### Rationale:
This is a dataset which will be useful to an Alex’s Grant recipient, Nicole. It primarily has Affymetrix and Agilent data, which we are prepared to process or replicate respectively, so it should be the easiest target to hit. It also will include a couple experiments which Jackie is planning on using to write a paper in the near term.

#### Requirements:
- [ ] Database refactor completed
- [ ] Nomad infrastructure working

#### Additional Notes
This will be a good first test of our new infrastructure/database. We should be able to get there fairly quickly, as in less than a month.

#### Rationale:
Building a compendium of nearly all publicly available expression data will require working with Agilent 2-color data. The plan is to use SCAN methodology on it, but a different function call (`SCAN.UPC::SCAN_TwoColor`) and different parameters than are used with Affymetrix data (e.g., no BrainArray package). The output of processing this data will enable decisions to be made regarding what to do for the larger Agilent corpus.

#### Requirements:
- [ ] Surveyor/downloader for NCBI GEO. This is necessary because ArrayExpress often does not have raw data for imported Agilent experiments in our experience.
- [ ] Detection of one- vs. two-color Agilent experiments (#89)
- [ ] Small amount of logic to run SCAN differently for Agilent data than Affymetrix (see [@kurtwheeler comment #87](https://github.com/data-refinery/data-refinery/issues/87#issuecomment-358358902)).

####  Additional Notes
An additional surveyor/downloader combo for NCBI GEO will be additional work, but the metadata retrieved from there is better than the metadata that gets copied to Array Express from NCBI GEO. In addition Array Express stopped replicating NCBI GEO 6 months ago so there is a growing body of data that we will not be able to access through Array Express alone.

#### Rationale:
This compendium is important for Jackie’s research, will be >10,000 samples in size, and will be a good starting point for future method development (e.g., aggregators). For this compendium, we’ll want to process Illumina microarray data with SCAN because there is a lot of it. Based on the results of experiments done on the results of Milestone #2, we may also want to implement something that will handle 2 color Agilent data. 

#### Requirements:
- [ ] Surveyor/downloader for NCBI GEO. This is necessary because ArrayExpress often does not have raw data for imported Illumina experiments in our experience. (See also Milestone 2 requirements.)
- [ ] Illumina Docker processor image
- [ ] Something for Agilent 2 color data?

#### Additional Notes
Once we have completed this milestone we will be very close to start scaling up the amounts of data we can process, since we’ll have surveyors, downloaders, and processors for all of the platforms we’re initially targeting. In addition, we’ll have processed a good amount of data so we’ll be able to start estimating the cost to process a sample.

**Comment by cgreene** [comment]
Looks like user tag should have been @jaclyn-taroni ☝️
